name: JMeter Performance Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  performance-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install JMeter
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jre
        latest_version=$(curl -s https://jmeter.apache.org/download_jmeter.cgi | grep -oP 'apache-jmeter-\K[0-9]+\.[0-9]+\.[0-9]+' | head -1)
        wget https://downloads.apache.org/jmeter/binaries/apache-jmeter-${latest_version}.tgz
        tar -xzf apache-jmeter-${latest_version}.tgz
        mv apache-jmeter-${latest_version} /opt/jmeter
        echo "JMeter Installed Successfully"

    - name: Run JMeter Test
      run: |
        mkdir -p jmeter-results
        /opt/jmeter/bin/jmeter -n -t test.jmx -l jmeter-results/results.jtl
        /opt/jmeter/bin/jmeter -g jmeter-results/results.jtl -o jmeter-results/html-report
        echo "JMeter Test and Report Generation Completed"

    - name: Upload HTML Report
      uses: actions/upload-artifact@v3
      with:
        name: jmeter-html-report
        path: jmeter-results/html-report